using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Core.Unums
{
    public class Maps
    {
        public enum StageId : byte
        {
            TD_PORTAKABA = 0x01,
            TD_REDROCK = 0x02,
            TD_LIBRARY = 0x03,
            TD_MSTATION = 0x04,
            TD_MIDNIGHTZONE = 0x05,
            TD_UPTOWN = 0x06,
            TD_BURNINGHALL = 0x07,
            TD_DSQUAD = 0x08,
            TD_CRACKDOWN = 0x09,
            TD_SAINTMANSION = 0x0a,
            TD_EASTERNROAD = 0x0b,
            TD_DOWNTOWN = 0x0c,
            TD_LUXVILLE = 0x0d,
            TD_BLOWCITY = 0x0e,
            TD_STORMTUBE = 0x0f,
            TD_BREAKDOWN = 0x11,
            TD_TRAININGCAMP = 0x12,
            TD_SENTRYBASE = 0x13,
            TD_DESERTCAMP = 0x14,
            TD_KICKPOINT = 0x15,
            TD_FACEROCK = 0x16,
            TD_SUPPLYBASE = 0x17,
            TD_SANDSTORM = 0x18,
            TD_SHOPPINGCENTER = 0x2d,
            TD_SAFARI = 0x2e,
            TD_DRAGONALLEY = 0x2f,
            TD_MACHUPICHU = 0x30,
            TD_TWOTOWERS = 0x32,
            TD_ANGKORRUINS = 0x39,
            TD_GHOSTTOWN = 0x3c,
            TD_GRANDBAZAAR = 0x3d,
            TD_UNDER23 = 0x3f,
            TD_TAIPEICITYMALL = 0x40,
            TD_SAFARI2 = 0x41,
            TD_METRO = 0x44,
            TD_RUSHHOUR = 0x4d,
            TD_CARGOPORT = 0x4e,
            TD_BLACKMAMBA = 0x4f,
            TD_HOLIDAY = 0x51,
            TD_WESTSTATION = 0x52,
            TD_HOUSEMUSEUM = 0x54,
            TD_WATERCOMPLEX = 0x58,
            TD_HOTELCAMOUFLAGE = 0x59,
            TD_PUMPKINHOLLOW = 0x55,
            TD_TESTMAP = 0x5f,
            TD_BATTLESHIP = 0x5a,
            TD_TEST = 0x61,
            TD_ROTHENVILLAGE = 0x56,
            TD_RAMPARTTOWN = 0x5d,
            TD_HINDRANCE = 0x62,
            TD_SEWERAGE = 0x63,
            TD_SLUMAREA = 0x64,
            TD_NEWLIBRARY = 0x65,
            BB_DOWNTOWN = 0x19,
            BB_LUXVILLE = 0x1a,
            BB_OUTPOST = 0x1b,
            BB_BLOWCITY = 0x1c,
            BB_STORMTUBE = 0x1d,
            BB_SENTRYBASE = 0x1e,
            BB_HOSPITAL = 0x1f,
            BB_DOWNTOWN2 = 0x20,
            BB_SHOPPINGCENTER = 0x21,
            BB_SANDSTORM = 0x22,
            BB_CARGOSHIP = 0x31,
            BB_AIRPORT = 0x42,
            BB_SAFEHOUSE = 0x50,
            BB_HARDROCK = 0x53,
            BB_RAMPARTTOWN = 0x5b,
            BB_BALLISTIC = 0x5c,
            BB_FALLUCITY = 0x5e,
            DS_BREAKDOWN = 0x23,
            DS_HELISPOT = 0x26,
            DF_BLACKPANTHER = 0x27,
            ES_BREEDINGNEST = 0x28,
            ES_DUPTOWN = 0x29,
            ES_DINOBREAKDOWN = 0x2a,
            ES_DINORUINS = 0x67,
            TUTORIAL = 0x2c,
            CC_CRACKDOWN = 0x33,
            CC_SAINTMANSION = 0x34,
            CC_DSQUAD = 0x35,
            CC_PORTAKABA = 0x36,
            CC_MSTATION = 0x37,
            CC_TRAININGCAMP = 0x38,
            CC_REDROCK = 0x3a,
            CC_SAFARI = 0x3b,
            CC_DINOLAB = 0x3e,
            CC_SAFARI2 = 0x43,
            UU_HOLIDAY = 0x57,
            EH_SANDSTORM = 0x66,
            EH_HOLIDAY = 0x60,
            EH_MERRYWHITEVILLAGE = 0x45,
        }

        /*public enum StageOption : ushort
        {
            NONE = 0x00,
            AI = 0x01,
            SNIPER = 0x04,
            ELIMINATE = 0x08,
            HEADHUNTER = 0x20,
            SHOTGUN = 0x80
        }*/
    }
}
