/*
 * C# Server Emulator Project Blackout / PointBlank
 * Authors: the__all
 * Copyright (C) 2015 | OZ-Network
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Core.Database.Tables;
using Core.Model;

namespace PointBlank.Network.ServerPacket
{
    class PROTOCOL_BASE_GET_SETTINGS_ACK : SendPacket
    {
        Account account;
        Player player;
        PlayerConfig config;

        public PROTOCOL_BASE_GET_SETTINGS_ACK(Account account) 
        {
            this.account = account;
        }

        public override void WriteImpl()
        {
            PlayersConfigTable.LoadTable();

            player = PlayersTable.players[account.AccountID];
            config = PlayersConfigTable.configuration[player.PlayerID];

            WriteH(0xA08);
            WriteD(1);
            WriteC((byte)2);
            WriteB(new byte[253]
            {
                Convert.ToByte(config.getBlood()),
                (byte) 0,
                Convert.ToByte(config.getVisibility()),
                Convert.ToByte(config.getMao()),
                Convert.ToByte(config.getConfig()),
                (byte) 0,
                (byte) 0,
                (byte) 0,
                Convert.ToByte(config.getAudioEnable()),
                (byte) 0,
                (byte) 0,
                (byte) 0,
                (byte) 0,
                (byte) 0,
                Convert.ToByte(config.getAudio1()),
                Convert.ToByte(config.getAudio2()),
                Convert.ToByte(config.getVision()),
                (byte) 0,
                Convert.ToByte(config.getMouseSensitivity()),
                (byte) 0,(byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 31,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 57,
        (byte) 248,
        (byte) 16,
        (byte) 0,
        (byte) 0,
        (byte) 10,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 13,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 32,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 28,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 44,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 40,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 38,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 15,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 1,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 27,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 29,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 5,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 26,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 16,
        (byte) 1,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 32,
        (byte) 0,
        (byte) 16,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 55,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 22,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 92,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 91,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 37,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 64,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 65,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 21,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 31,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 35,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 12,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 14,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 49,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 50,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 70,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 66,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 11,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 58,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        byte.MaxValue,
        byte.MaxValue,
        byte.MaxValue,
        byte.MaxValue,
        (byte) 1,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 1,
        (byte) 0 
      }); 
     }
    }
}
